# Generated by Django 5.0.7 on 2024-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='chat_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
