# Generated by Django 5.0.7 on 2024-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Не оплачен'), ('paid', 'Оплачен'), ('in_progress', 'В работе'), ('completed', 'Выполнен'), ('cancelled', 'Отменен')], default='created', max_length=20),
        ),
    ]
